# Generated by Django 5.1.6 on 2025-03-18 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnephysique',
            old_name='adresse',
            new_name='addresse',
        ),
    ]
