# Generated by Django 5.1.6 on 2025-02-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annexe', models.IntegerField()),
                ('numero_secteur', models.IntegerField(blank=True, null=True)),
                ('numero_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('lotissement', models.CharField(blank=True, max_length=255, null=True)),
                ('consistance', models.CharField(blank=True, max_length=255, null=True)),
                ('avenue', models.CharField(blank=True, max_length=255, null=True)),
                ('rue', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titre', models.IntegerField()),
                ('surface_totale', models.IntegerField(blank=True, null=True)),
                ('surface_taxable', models.IntegerField(blank=True, null=True)),
                ('sdau', models.CharField(blank=True, max_length=255, null=True)),
                ('date_eclatement', models.DateField(blank=True, null=True)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cnie', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('rc', models.IntegerField()),
                ('raison_sociale', models.CharField(max_length=255)),
                ('if_entreprise', models.IntegerField(blank=True, null=True)),
                ('ice', models.CharField(blank=True, max_length=255, null=True)),
                ('type_demande', models.TextField()),
                ('nature_demande', models.TextField()),
                ('numero_dossier', models.CharField(max_length=255)),
                ('date_retrait', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
