# Generated by Django 4.2 on 2025-02-21 15:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_parcelle'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceVert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_espace', models.CharField(max_length=255)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre_arbres', models.IntegerField()),
                ('gestionnaire', models.CharField(max_length=255)),
                ('statut', models.CharField(max_length=255)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.IntegerField()),
                ('numero_secteur', models.IntegerField(blank=True, null=True)),
                ('numero_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('lotissement', models.CharField(blank=True, max_length=255, null=True)),
                ('consistance', models.CharField(blank=True, max_length=255, null=True)),
                ('avenue', models.CharField(blank=True, max_length=255, null=True)),
                ('rue', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titre', models.IntegerField()),
                ('surface_totale', models.FloatField(blank=True, null=True)),
                ('surface_taxable', models.FloatField(blank=True, null=True)),
                ('sdau', models.CharField(blank=True, max_length=255, null=True)),
                ('date_eclatement', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SportCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_etablissement', models.CharField(max_length=255)),
                ('activite_principale', models.CharField(max_length=255)),
                ('capacite', models.IntegerField()),
                ('horaires_ouverture', models.CharField(max_length=255)),
                ('gestionnaire', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Voirie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_voirie', models.CharField(max_length=255)),
                ('largeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('etat', models.CharField(max_length=255)),
                ('priorite', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='Parcelle',
        ),
    ]
