# Generated by Django 5.1.6 on 2025-02-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_espacevert_principal_sportculture_voirie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inspection_technicien', models.CharField(max_length=255)),
                ('type_occupation', models.CharField(choices=[('communal_nu', 'الملك الجماعي عاري'), ('communal_couvert', 'الملك الجماعي مغطى'), ('panneau', 'لوحة إشهارية'), ('installation', 'نصب اشهاري')], max_length=50)),
                ('surface', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inspection',
            },
        ),
        migrations.CreateModel(
            name='PaiementPermisUrbanisme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('quittance', models.IntegerField()),
                ('date_paiement', models.DateField()),
                ('montant_occupation', models.FloatField(blank=True, null=True)),
                ('quittance_occupation', models.IntegerField(blank=True, null=True)),
                ('date_paiement_occupation', models.DateField(blank=True, null=True)),
                ('periode_occupation', models.IntegerField(blank=True, null=True)),
                ('rubrique', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paiement_permis_urbanisme',
            },
        ),
        migrations.CreateModel(
            name='PaiementTNB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxe_tnb', models.FloatField()),
                ('quittance', models.IntegerField()),
                ('date_paiement', models.DateField()),
                ('rubrique', models.CharField(max_length=255)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paiement_tnb',
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annexe', models.IntegerField(help_text='Annexe')),
                ('numero_secteur', models.IntegerField(blank=True, null=True)),
                ('numero_lot', models.CharField(blank=True, max_length=255, null=True)),
                ('lotissement', models.CharField(blank=True, max_length=255, null=True)),
                ('consistance', models.CharField(blank=True, max_length=255, null=True)),
                ('avenue', models.CharField(blank=True, max_length=255, null=True)),
                ('rue', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('titre', models.IntegerField()),
                ('surface_totale', models.FloatField(blank=True, null=True)),
                ('surface_taxable', models.FloatField(blank=True, null=True)),
                ('sdau', models.CharField(blank=True, max_length=255, null=True)),
                ('date_eclatement', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parcelle',
            },
        ),
        migrations.CreateModel(
            name='Permis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('construction', 'Permis de construction'), ('habiter', "Permis d'habiter"), ('reparation', 'Permis de réparation'), ('demolition', 'Permis de démolition'), ('renouvellement', "Permis de renouvellement d'occupation du domaine public"), ('segmentation', "Permis d'établissement de segmentation"), ('groupe_residentiel', 'Permis pour créer un groupe résidentiel'), ('petits_projets', 'Permis de construire pour petits projets'), ('grands_projets', 'Permis de construire pour grands projets')], max_length=50)),
                ('nature_demande', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('numero_dossier', models.CharField(max_length=255)),
                ('numero_titre', models.IntegerField()),
                ('date_retrait', models.DateField()),
                ('mois_concerne', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_decision', models.CharField(max_length=255)),
                ('date_permis', models.DateField()),
            ],
            options={
                'db_table': 'permis',
            },
        ),
        migrations.CreateModel(
            name='PermisCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorise', models.BooleanField(default=False)),
                ('exonere', models.BooleanField(default=False)),
                ('activite', models.CharField(max_length=255)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('annexe', models.IntegerField()),
                ('arrondissement', models.IntegerField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_permis', models.DateField()),
                ('numero_permis', models.CharField(max_length=255)),
                ('reparations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permis_commercial',
            },
        ),
        migrations.CreateModel(
            name='PersonneMorale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc', models.IntegerField()),
                ('raison_sociale', models.CharField(max_length=255)),
                ('if_field', models.IntegerField(blank=True, db_column='if', null=True)),
                ('ice', models.TextField(blank=True, null=True)),
                ('adresse_domicile', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personne_morale',
            },
        ),
        migrations.CreateModel(
            name='PersonnePhysique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('cnie', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personne_physique',
            },
        ),
        migrations.CreateModel(
            name='SuiviTravaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('phase_construction', models.CharField(choices=[('terrains_nus', 'Terrains nus'), ('chantier', 'Chantier'), ('projet_acheve', 'Projet achevé')], max_length=50)),
            ],
            options={
                'db_table': 'suivi_travaux',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Principal',
        ),
        migrations.AlterField(
            model_name='espacevert',
            name='date_creation',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='espacevert',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='espacevert',
            name='surface',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sportculture',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sportculture',
            name='horaires_ouverture',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voirie',
            name='largeur',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='voirie',
            name='observations',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='espacevert',
            table='espace_vert',
        ),
        migrations.AlterModelTable(
            name='sportculture',
            table='sport_culture',
        ),
        migrations.AlterModelTable(
            name='voirie',
            table='voirie',
        ),
        migrations.AddField(
            model_name='paiementpermisurbanisme',
            name='ref_permis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.permis'),
        ),
    ]
