# Generated by Django 5.1.6 on 2025-02-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_item'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='espacevert',
            table=None,
        ),
    ]
