# Generated by Django 5.1.6 on 2025-02-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_espacevert_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='voirie',
            table=None,
        ),
    ]
