# Generated by Django 5.1.6 on 2025-02-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_item_alter_sportculture_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisRegie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autorise', models.BooleanField(default=False)),
                ('exonere', models.BooleanField(default=False)),
                ('activite', models.CharField(max_length=255)),
                ('specialite', models.CharField(blank=True, max_length=255, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('annexe', models.IntegerField()),
                ('arrondissement', models.IntegerField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_de_permis', models.DateField()),
                ('numero_de_permis', models.CharField(max_length=255, unique=True)),
                ('reparations', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
